# -*- coding: utf-8 -*-
"""AI_Assignment_Driver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SkLzOTS9IPVfiMFJajj62FpmWD1HRoW
"""

import streamlit as st
import joblib
import numpy as np

st.title("Diabetes Prediction System")

st.write("Enter patient details to predict diabetes risk.")

# Load models and tools
scaler = joblib.load("scaler.joblib")
gender_encoder = joblib.load("gender_encoder.joblib")
smoke_encoder = joblib.load("smoke_encoder.joblib")
accuracy = joblib.load("accuracy.joblib")
cm_dict = joblib.load("confusion_matrix.joblib")

# Model selection
model_choice = st.selectbox(
    "Select Machine Learning Model",
    ("ANN", "KNN", "SVM")
)

# Load model
if model_choice == "ANN":
    model = joblib.load("ann_model.joblib")
elif model_choice == "KNN":
    model = joblib.load("knn_model.joblib")
else:
    model = joblib.load("svm_model.joblib")

# -------------------------
# UI Inputs
# -------------------------
gender = st.selectbox("Gender", ["Female", "Male"])
age = st.number_input("Age", 1, 120)

hypertension = st.selectbox("Hypertension", [0, 1])
heart_disease = st.selectbox("Heart Disease History", [0, 1])

smoking = st.selectbox(
    "Smoking History",
    ["never", "No Info", "current", "former", "ever", "not current"]
)

bmi = st.number_input("BMI", 10.0, 60.0)
hba1c = st.number_input("HbA1c Level", 3.0, 15.0)
glucose = st.number_input("Blood Glucose Level", 50, 300)

# -------------------------
# Prediction
# -------------------------
if st.button("Predict Diabetes Risk"):

    # Encode categorical
    gender_encoded = gender_encoder.transform([gender])[0]
    smoking_encoded = smoke_encoder.transform([smoking])[0]

    # Input array
    input_data = np.array([[gender_encoded, age, hypertension,
                            heart_disease, smoking_encoded,
                            bmi, hba1c, glucose]])

    # Scale
    input_scaled = scaler.transform(input_data)

    # Prediction
    prediction = model.predict(input_scaled)
    probability = model.predict_proba(input_scaled)

    # Extract probability
    prob_no = probability[0][0]
    prob_yes = probability[0][1]

    # -------------------------
    # Display result
    # -------------------------
    st.subheader("Prediction Result")

    if prediction[0] == 1:
        st.error(f"⚠️ Diabetes Risk Detected ({prob_yes*100:.2f}%)")
    else:
        st.success(f"✅ No Diabetes Detected ({prob_no*100:.2f}%)")

    # Show probabilities
    st.write("### Prediction Probability")
    st.write(f"No Diabetes: {prob_no*100:.2f}%")
    st.write(f"Diabetes: {prob_yes*100:.2f}%")

st.subheader("Model Accuracy Comparison")

acc_df = pd.DataFrame({
    "Model": ["KNN", "SVM", "ANN"],
    "Accuracy (%)": [
        accuracy["KNN"] * 100,
        accuracy["SVM"] * 100,
        accuracy["ANN"] * 100
    ]
})

st.table(acc_df)

st.subheader("Accuracy Comparison Chart")

chart_data = pd.DataFrame({
    "Model": ["KNN", "SVM", "ANN"],
    "Accuracy": [
        accuracy["KNN"],
        accuracy["SVM"],
        accuracy["ANN"]
    ]
})

st.bar_chart(chart_data.set_index("Model"))

st.subheader("Confusion Matrix")

selected_model = st.selectbox(
    "Select Model for Confusion Matrix",
    ("KNN", "SVM", "ANN")
)

cm = cm_dict[selected_model]

cm_df = pd.DataFrame(
    cm,
    index=["Actual No", "Actual Yes"],
    columns=["Predicted No", "Predicted Yes"]
)

st.write(f"{selected_model} Confusion Matrix")
st.table(cm_df)

