# -*- coding: utf-8 -*-
"""AI_Assignment_Driver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SkLzOTS9IPVfiMFJajj62FpmWD1HRoW
"""
import streamlit as st
import joblib
import numpy as np

# Example: load ANN model
model = joblib.load("ann_model.joblib")

# Example input data (replace with user input from Streamlit)
input_data = np.array([[63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1]])

# Make prediction
prediction = model.predict(input_data)

if prediction[0] == 1:
    print("⚠️ Heart Disease Risk Detected")
else:
    print("✅ No Heart Disease Detected")
