# -*- coding: utf-8 -*-
"""AI_Assignment_Driver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SkLzOTS9IPVfiMFJajj62FpmWD1HRoW
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
st.title("Diabetes Prediction System")

st.write("Enter patient details to predict diabetes risk.")

# Load models and tools
scaler = joblib.load("scaler.joblib")
gender_encoder = joblib.load("gender_encoder.joblib")
smoke_encoder = joblib.load("smoke_encoder.joblib")
accuracy = joblib.load("accuracy.joblib")
cm_dict = joblib.load("confusion_matrix.joblib")

# Model selection
model_choice = st.selectbox(
    "Select Machine Learning Model",
    ("ANN", "KNN", "SVM")
)

# Load model
if model_choice == "ANN":
    model = joblib.load("ann_model.joblib")
elif model_choice == "KNN":
    model = joblib.load("knn_model.joblib")
else:
    model = joblib.load("svm_model.joblib")

# -------------------------
# UI Inputs
# -------------------------
gender = st.selectbox("Gender", ["Female", "Male"])
age = st.number_input("Age", 1, 120)

hypertension = st.selectbox("Hypertension", [0, 1])
heart_disease = st.selectbox("Heart Disease History", [0, 1])

smoking = st.selectbox(
    "Smoking History",
    ["never", "No Info", "current", "former", "ever", "not current"]
)

bmi = st.number_input("BMI", 10.0, 60.0)
hba1c = st.number_input("HbA1c Level", 3.0, 15.0)
glucose = st.number_input("Blood Glucose Level", 50, 300)

# -------------------------
# Prediction
# -------------------------
if st.button("Predict Diabetes Risk"):

    # Encode categorical
    gender_encoded = gender_encoder.transform([gender])[0]
    smoking_encoded = smoke_encoder.transform([smoking])[0]

    # Input array
    input_data = np.array([[gender_encoded, age, hypertension,
                            heart_disease, smoking_encoded,
                            bmi, hba1c, glucose]])

    # Scale
    input_scaled = scaler.transform(input_data)

    # Prediction
    prediction = model.predict(input_scaled)
    probability = model.predict_proba(input_scaled)

    # Extract probability
    prob_no = probability[0][0]
    prob_yes = probability[0][1]

    # -------------------------
    # Display result
    # -------------------------
    st.subheader("Prediction Result")

    if prediction[0] == 1:
        st.error(f"⚠️ Diabetes Risk Detected ({prob_yes*100:.2f}%)")
    else:
        st.success(f"✅ No Diabetes Detected ({prob_no*100:.2f}%)")

    # Show probabilities
    st.write("### Prediction Probability")
    st.write(f"No Diabetes: {prob_no*100:.2f}%")
    st.write(f"Diabetes: {prob_yes*100:.2f}%")

import pandas as pd
import matplotlib.pyplot as plt

# Load saved metrics
accuracy = joblib.load("accuracy.joblib")
cm_dict = joblib.load("confusion_matrix.joblib")
report_dict = joblib.load("report.joblib")
roc_dict = joblib.load("roc.joblib")

st.header("📊 Model Performance Dashboard")

# -------------------------
# Accuracy Table + Chart
# -------------------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("Accuracy Table")
    acc_df = pd.DataFrame({
        "Model": ["KNN", "SVM", "ANN"],
        "Accuracy (%)": [
            accuracy["KNN"]*100,
            accuracy["SVM"]*100,
            accuracy["ANN"]*100
        ]
    })
    st.table(acc_df)

with col2:
    st.subheader("Accuracy Chart")
    st.bar_chart(acc_df.set_index("Model"))

# -------------------------
# Model Selection
# -------------------------
st.subheader("Detailed Model Analysis")

selected_model = st.selectbox(
    "Select Model",
    ("KNN", "SVM", "ANN")
)

# -------------------------
# Confusion Matrix
# -------------------------
st.write("### Confusion Matrix")

cm = cm_dict[selected_model]
cm_df = pd.DataFrame(
    cm,
    index=["Actual No", "Actual Yes"],
    columns=["Predicted No", "Predicted Yes"]
)

st.table(cm_df)

# -------------------------
# Classification Report
# -------------------------
st.write("### Precision / Recall / F1-score")

report = report_dict[selected_model]

report_df = pd.DataFrame(report).transpose()
st.dataframe(report_df)

# -------------------------
# ROC Curve
# -------------------------
st.write("### ROC Curve")

roc = roc_dict[selected_model]

fig, ax = plt.subplots()
ax.plot(roc["fpr"], roc["tpr"], label=f"AUC = {roc['auc']:.2f}")
ax.plot([0,1], [0,1], linestyle="--")  # diagonal line
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title(f"{selected_model} ROC Curve")
ax.legend()

st.pyplot(fig)